const LANGUAGE_DATA = [
    { code: "auto", name: "Auto (System Default)" },
    { code: "en-US", name: "English (US)" },
    { code: "en-CA", name: "English (Canada)" },
    { code: "fr-CA", name: "Français (Canada)" },
    { code: "es-MX", name: "Español (México)" },
    { code: "es-AR", name: "Español (Argentina)" },
    { code: "es-CL", name: "Español (Chile)" },
    { code: "es-CO", name: "Español (Colombia)" },
    { code: "pt-BR", name: "Português (Brasil)" },
    { code: "en-GB", name: "English (UK)" },
    { code: "en-IE", name: "English (Ireland)" },
    { code: "fr-FR", name: "Français (France)" },
    { code: "de-DE", name: "Deutsch (Deutschland)" },
    { code: "it-IT", name: "Italiano (Italia)" },
    { code: "es-ES", name: "Español (España)" },
    { code: "pt-PT", name: "Português (Portugal)" },
    { code: "nl-NL", name: "Nederlands (Nederland)" },
    { code: "nl-BE", name: "Nederlands (België)" },
    { code: "fr-BE", name: "Français (Belgique)" },
    { code: "de-CH", name: "Deutsch (Schweiz)" },
    { code: "fr-CH", name: "Français (Suisse)" },
    { code: "it-CH", name: "Italiano (Svizzera)" },
    { code: "de-AT", name: "Deutsch (Österreich)" },
    { code: "sv-SE", name: "Svenska (Sverige)" },
    { code: "no-NO", name: "Norsk (Norge)" },
    { code: "da-DK", name: "Dansk (Danmark)" },
    { code: "fi-FI", name: "Suomi (Suomi)" },
    { code: "pl-PL", name: "Polski (Polska)" },
    { code: "cs-CZ", name: "Čeština (Česko)" },
    { code: "hu-HU", name: "Magyar (Magyarország)" },
    { code: "ro-RO", name: "Română (România)" },
    { code: "el-GR", name: "Ελληνικά (Ελλάδα)" },
    { code: "tr-TR", name: "Türkçe (Türkiye)" },
    { code: "ru-RU", name: "Русский (Россия)" },
    { code: "uk-UA", name: "Українська (Україна)" },
    { code: "zh-CN", name: "中文 (中国大陆)" },
    { code: "zh-TW", name: "中文 (台湾)" },
    { code: "zh-HK", name: "中文 (香港)" },
    { code: "ja-JP", name: "日本語 (日本)" },
    { code: "ko-KR", name: "한국어 (대한민국)" },
    { code: "th-TH", name: "ไทย (ไทย)" },
    { code: "vi-VN", name: "Tiếng Việt (Việt Nam)" },
    { code: "id-ID", name: "Bahasa Indonesia (Indonesia)" },
    { code: "ms-MY", name: "Bahasa Melayu (Malaysia)" },
    { code: "fil-PH", name: "Filipino (Pilipinas)" },
    { code: "en-IN", name: "English (India)" },
    { code: "hi-IN", name: "हिन्दी (भारत)" },
    { code: "en-AU", name: "English (Australia)" },
    { code: "en-NZ", name: "English (New Zealand)" },
    { code: "ar-SA", name: "العربية (السعودية)" },
    { code: "ar-AE", name: "العربية (الإمارات)" },
    { code: "he-IL", name: "עברית (ישראל)" },
    { code: "en-ZA", name: "English (South Africa)" }
];
window.LANGUAGE_DATA = LANGUAGE_DATA;
